# Generated by Django 2.1.1 on 2018-09-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='text',
        ),
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='content',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
