# Generated by Django 2.1.1 on 2018-09-12 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iqbox', '0002_auto_20180912_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
